// Structures and values taken from the usb audio spec. This is rather platform independent


#ifndef _USBAUDIOSPEC_
#define _USBAUDIOSPEC_

/** Class-specific desriptor types */
typedef enum USB_AUDIO_DESCRIPTOR_TYPE {
	USB_DESC_AUDIO_DEVICE				= 0x21,
	USB_DESC_AUDIO_CONFIGURATION		= 0x22,
	USB_DESC_AUDIO_STRING				= 0x23,
	USB_DESC_AUDIO_INTERFACE			= 0x24,
	USB_DESC_AUDIO_ENDPOINT				= 0x25
} USB_AUDIO_DESCRIPTOR_TYPE;

/** USB Audio interface subclasses */
typedef enum USB_AUDIO_INTERFACE_SUBCLASS_CODE {
	USB_AUDIO_INTERFACE_AUDIOCONTROL	= 0x01,
	USB_AUDIO_INTERFACE_AUDIOSTREAMING	= 0x02,
	USB_AUDIO_INTERFACE_MIDISTREAMING	= 0x03
} USB_AUDIO_INTERFACE_SUBCLASS_CODE;

/** USB Audio endpoint subclasses */
typedef enum USB_AUDIO_ENDPOINT_SUBCLASS_CODE {
	USB_AUDIO_ENDPOINT_GENERAL	= 0x01
} USB_AUDIO_ENDPOINT_SUBCLASS_CODE;

/** USB Audio Control interface-specific descriptor subclasses */
typedef enum USB_AUDIO_CONTROL_INTERFACE_DESCRIPTOR_SUBTYPE {
	USB_AUDIO_CONTROL_INTERFACE_DESCRIPTOR_HEADER			= 0x01,
	USB_AUDIO_CONTROL_INTERFACE_DESCRIPTOR_INPUT_TERMINAL	= 0x02,
	USB_AUDIO_CONTROL_INTERFACE_DESCRIPTOR_OUTPUT_TERMINAL	= 0x03,
	USB_AUDIO_CONTROL_INTERFACE_DESCRIPTOR_MIXER_UNIT		= 0x04,
	USB_AUDIO_CONTROL_INTERFACE_DESCRIPTOR_SELECTOR_UNIT	= 0x05,
	USB_AUDIO_CONTROL_INTERFACE_DESCRIPTOR_FEATURE_UNIT		= 0x06,
	USB_AUDIO_CONTROL_INTERFACE_DESCRIPTOR_PROCESSING_UNIT	= 0x07,
	USB_AUDIO_CONTROL_INTERFACE_DESCRIPTOR_EXTENSION_UNIT	= 0x08
} USB_AUDIO_CONTROL_INTERFACE_DESCRIPTOR_SUBTYPE;

/** USB Audio Stream interface-specific descriptor subclasses */
typedef enum USB_AUDIO_STREAM_INTERFACE_DESCRIPTOR_SUBTYPE {
	USB_AUDIO_STREAM_INTERFACE_DESCRIPTOR_GENERAL			= 0x01,
	USB_AUDIO_STREAM_INTERFACE_DESCRIPTOR_FORMAT_TYPE		= 0x02,
	USB_AUDIO_STREAM_INTERFACE_DESCRIPTOR_FORMAT_SPECIFIC	= 0x03
} USB_AUDIO_STREAM_INTERFACE_DESCRIPTOR_SUBTYPE;

/** USB Audio endpoint-specific descriptor subclasses */
typedef enum USB_AUDIO_ENDPOINT_DESCRIPTOR_SUBTYPE {
	USB_AUDIO_ENDPOINT_DESCRIPTOR_UNDEFINED					= 0x01,
	USB_AUDIO_ENDPOINT_DESCRIPTOR_GENERAL					= 0x02
} USB_AUDIO_ENDPOINT_DESCRIPTOR_SUBTYPE;

/** endpoint flags for isoch audio data endpoint descriptors */
typedef enum USB_AUDIO_ENDPOINT_FLAGS {
	USB_AUDIO_ENDPOINT_FLAG_SAMPLING_FREQUENCY_SUPPORTED	= 0x01,
	USB_AUDIO_ENDPOINT_FLAG_PITCH_SUPPORTED					= 0x02,
	USB_AUDIO_ENDPOINT_FLAG_MAX_PACKET_SIZE_ONLY			= 0x80,
} USB_AUDIO_ENDPOINT_FLAGS;

/** units for isoch audio data endpoint descriptors */
typedef enum USB_AUDIO_LOCKDELAY_UNITS {
	USB_AUDIO_LOCKDELAY_UNDEFINED							= 0x00,
	USB_AUDIO_LOCKDELAY_MILLISECONDS						= 0x01,
	USB_AUDIO_LOCKDELAY_SAMPLES								= 0x02
} USB_AUDIO_LOCKDELAY_UNITS;

/** values for USB Audio wFormatTag (Format types 1-3, USB Audio Format Spec, Appendix A) */
typedef enum USB_AUDIO_FORMATTAG {
	USB_AUDIO_FORMAT_I_UNDEFINED		= 0x0000,
	USB_AUDIO_FORMAT_I_PCM				= 0x0001,
	USB_AUDIO_FORMAT_I_PCM8				= 0x0002,
	USB_AUDIO_FORMAT_I_IEEE_FLOAT		= 0x0003,
	USB_AUDIO_FORMAT_I_ALAW				= 0x0004,
	USB_AUDIO_FORMAT_I_MULAW			= 0x0005,
	USB_AUDIO_FORMAT_II_UNDEFINED		= 0x1000,
	USB_AUDIO_FORMAT_II_MPEG			= 0x1001,
	USB_AUDIO_FORMAT_II_AC3				= 0x1002,
	USB_AUDIO_FORMAT_III_UNDEFINED		= 0x2000,
	USB_AUDIO_FORMAT_III_AC3			= 0x2001,
	USB_AUDIO_FORMAT_III_MPEG1LAYER1	= 0x2002,
	USB_AUDIO_FORMAT_III_MPEG1LAYER2	= 0x2003,
	USB_AUDIO_FORMAT_III_MPEG1LAYER3	= 0x2003,
	USB_AUDIO_FORMAT_III_MPEG2_NOEXT	= 0x2003,
	USB_AUDIO_FORMAT_III_MPEG2_EXT		= 0x2004,
	USB_AUDIO_FORMAT_III_MPEG2LAYER1LS	= 0x2005,
	USB_AUDIO_FORMAT_III_MPEG2LAYER2LS	= 0x2006,
	USB_AUDIO_FORMAT_III_MPEG2LAYER3LS	= 0x2006
} USB_AUDIO_FORMATTAG;

/** USB Audio format types (USB Audio Format Spec, Appendix A.2) */
typedef enum USB_AUDIO_FORMATTYPE {
	USB_AUDIO_FORMATTYPE_UNDEFINED = 0,
	USB_AUDIO_FORMATTYPE_I = 1,
	USB_AUDIO_FORMATTYPE_II = 2,
	USB_AUDIO_FORMATTYPE_III = 3
} USB_AUDIO_FORMATTYPE;

/** USB Audio class-specific request codes (USB Audio Spec Appendix A.9)
 * Usually sent to control interface. */
typedef enum USB_AUDIO_REQUEST {
	USB_AUDIO_REQ_UNDEFINED			= 0x00,
	USB_AUDIO_REQ_SET_CUR			= 0x01,
	USB_AUDIO_REQ_SET_MIN			= 0x02,
	USB_AUDIO_REQ_SET_MAX			= 0x03,
	USB_AUDIO_REQ_SET_RES			= 0x04,
	USB_AUDIO_REQ_SET_MEM			= 0x05,
	USB_AUDIO_REQ_GET_CUR			= 0x81,
	USB_AUDIO_REQ_GET_MIN			= 0x82,
	USB_AUDIO_REQ_GET_MAX			= 0x83,
	USB_AUDIO_REQ_GET_RES			= 0x84,
	USB_AUDIO_REQ_GET_MEM			= 0x85,
	USB_AUDIO_REQ_GET_STAT			= 0xff
} USB_AUDIO_REQUEST;
	
/** USB Audio control selectors, sent to units (USB Audio Spec A.10) */
typedef enum USB_AUDIO_CONTROL_SELECTOR {
	USB_AUDIO_CSEL_TERMINAL_COPY_PROTECT	= 0x01,
	USB_AUDIO_CSEL_FEATURE_MUTE				= 0x01,
	USB_AUDIO_CSEL_FEATURE_VOLUME			= 0x02,
	USB_AUDIO_CSEL_FEATURE_BASS				= 0x03,
	USB_AUDIO_CSEL_FEATURE_MID				= 0x04,
	USB_AUDIO_CSEL_FEATURE_TREBLE			= 0x05,
	USB_AUDIO_CSEL_FEATURE_EQ				= 0x06,
	USB_AUDIO_CSEL_FEATURE_AUTOGAIN			= 0x07,
	USB_AUDIO_CSEL_FEATURE_DELAY			= 0x08,
	USB_AUDIO_CSEL_FEATURE_BASSBOOST		= 0x09,
	USB_AUDIO_CSEL_FEATURE_LOUDNESS			= 0x0A,
	USB_AUDIO_CSEL_UPDOWNMIX_ENABLE			= 0x01,
	USB_AUDIO_CSEL_UPDOWNMIX_SELECT			= 0x02,
	USB_AUDIO_CSEL_DOLBYPL_ENABLE			= 0x01,
	USB_AUDIO_CSEL_DOLBYPL_SELECT			= 0x02,
	USB_AUDIO_CSEL_3D_ENABLE				= 0x01,
	USB_AUDIO_CSEL_3D_SPACIOUSNESS			= 0x02,
	USB_AUDIO_CSEL_REVERB_ENABLE			= 0x01,
	USB_AUDIO_CSEL_REVERB_LEVEL				= 0x02,
	USB_AUDIO_CSEL_REVERB_TIME				= 0x03,
	USB_AUDIO_CSEL_REVERB_FEEDBACK			= 0x04,
	USB_AUDIO_CSEL_CHORUS_ENABLE			= 0x01,
	USB_AUDIO_CSEL_CHORUS_LEVEL				= 0x02,
	USB_AUDIO_CSEL_CHORUS_RATE				= 0x03,
	USB_AUDIO_CSEL_CHORUS_DEPTH				= 0x04,
	USB_AUDIO_CSEL_COMPR_ENABLE				= 0x01,
	USB_AUDIO_CSEL_COMPR_RATE				= 0x02,
	USB_AUDIO_CSEL_COMPR_MAXAMPL			= 0x03,
	USB_AUDIO_CSEL_COMPR_THRESHOLD			= 0x04,
	USB_AUDIO_CSEL_COMPR_ATTACK				= 0x05,
	USB_AUDIO_CSEL_COMPR_RELEASE			= 0x06,
	USB_AUDIO_CSEL_EXTENSION_ENABLE			= 0x01,
	USB_AUDIO_CSEL_ENDPOINT_FREQ			= 0x01,
	USB_AUDIO_CSEL_ENDPOINT_PITCH			= 0x02
} USB_AUDIO_CONTROL_SELECTOR;
	
	
	
#endif